// Author: Robert Massey | Created: 2026-07-13 | Module: @attune-sb/form-engine
// Purpose: Registry mapping field type → display name, icon, and default config.
// Used by form builders and field palette UIs.
// Ported verbatim from the enterprise @attune/form-engine.
import type { FieldType } from '@attune-sb/shared-types';

export interface FieldTypeDefinition {
  readonly type: FieldType;
  readonly label: string;
  readonly category: 'text' | 'choice' | 'date' | 'capture' | 'layout' | 'calculated';
  readonly icon: string;
  readonly defaultConfig: Record<string, unknown>;
  readonly supportsRequired: boolean;
  readonly supportsConditional: boolean;
}

export const FIELD_DEFINITIONS: FieldTypeDefinition[] = [
  {
    type: 'text',
    label: 'Text',
    category: 'text',
    icon: 'T',
    defaultConfig: { placeholder: '' },
    supportsRequired: true,
    supportsConditional: true,
  },
  {
    type: 'multiline',
    label: 'Multiline Text',
    category: 'text',
    icon: '¶',
    defaultConfig: { rows: 4, placeholder: '' },
    supportsRequired: true,
    supportsConditional: true,
  },
  {
    type: 'textarea',
    label: 'Textarea',
    category: 'text',
    icon: '¶',
    defaultConfig: { rows: 6, placeholder: '' },
    supportsRequired: true,
    supportsConditional: true,
  },
  {
    type: 'number',
    label: 'Number',
    category: 'text',
    icon: '#',
    defaultConfig: { placeholder: '0' },
    supportsRequired: true,
    supportsConditional: true,
  },
  {
    type: 'email',
    label: 'Email',
    category: 'text',
    icon: '@',
    defaultConfig: {},
    supportsRequired: true,
    supportsConditional: true,
  },
  {
    type: 'phone',
    label: 'Phone',
    category: 'text',
    icon: '☎',
    defaultConfig: {},
    supportsRequired: true,
    supportsConditional: true,
  },
  {
    type: 'url',
    label: 'URL',
    category: 'text',
    icon: '🔗',
    defaultConfig: {},
    supportsRequired: true,
    supportsConditional: true,
  },
  {
    type: 'dynamiclist',
    label: 'Dynamic List',
    category: 'text',
    icon: '≡',
    defaultConfig: {},
    supportsRequired: true,
    supportsConditional: true,
  },
  {
    type: 'dropdown',
    label: 'Dropdown',
    category: 'choice',
    icon: '▾',
    defaultConfig: { options: [] },
    supportsRequired: true,
    supportsConditional: true,
  },
  {
    type: 'multiselect',
    label: 'Multi-Select',
    category: 'choice',
    icon: '☑',
    defaultConfig: { options: [] },
    supportsRequired: true,
    supportsConditional: true,
  },
  {
    type: 'select',
    label: 'Select',
    category: 'choice',
    icon: '▾',
    defaultConfig: { options: [] },
    supportsRequired: true,
    supportsConditional: true,
  },
  {
    type: 'radio',
    label: 'Radio Buttons',
    category: 'choice',
    icon: '◎',
    defaultConfig: { options: [] },
    supportsRequired: true,
    supportsConditional: true,
  },
  {
    type: 'checkbox',
    label: 'Checkbox',
    category: 'choice',
    icon: '☐',
    defaultConfig: {},
    supportsRequired: false,
    supportsConditional: true,
  },
  {
    type: 'yesno',
    label: 'Yes / No',
    category: 'choice',
    icon: '✓✗',
    defaultConfig: {},
    supportsRequired: true,
    supportsConditional: true,
  },
  {
    type: 'toggle',
    label: 'Toggle',
    category: 'choice',
    icon: '⏻',
    defaultConfig: {},
    supportsRequired: false,
    supportsConditional: true,
  },
  {
    type: 'date',
    label: 'Date',
    category: 'date',
    icon: '📅',
    defaultConfig: {},
    supportsRequired: true,
    supportsConditional: true,
  },
  {
    type: 'time',
    label: 'Time',
    category: 'date',
    icon: '🕐',
    defaultConfig: {},
    supportsRequired: true,
    supportsConditional: true,
  },
  {
    type: 'datetime',
    label: 'Date & Time',
    category: 'date',
    icon: '📅',
    defaultConfig: {},
    supportsRequired: true,
    supportsConditional: true,
  },
  {
    type: 'eventtimestamp',
    label: 'Event Timestamp',
    category: 'date',
    icon: '⏱',
    defaultConfig: {},
    supportsRequired: true,
    supportsConditional: false,
  },
  {
    type: 'photo',
    label: 'Photo',
    category: 'capture',
    icon: '📷',
    defaultConfig: {},
    supportsRequired: true,
    supportsConditional: false,
  },
  {
    type: 'signature',
    label: 'Signature',
    category: 'capture',
    icon: '✏️',
    defaultConfig: {},
    supportsRequired: true,
    supportsConditional: false,
  },
  {
    type: 'barcode',
    label: 'Barcode / QR',
    category: 'capture',
    icon: '▦',
    defaultConfig: {},
    supportsRequired: true,
    supportsConditional: false,
  },
  {
    type: 'gps',
    label: 'GPS Location',
    category: 'capture',
    icon: '📍',
    defaultConfig: {},
    supportsRequired: true,
    supportsConditional: false,
  },
  {
    type: 'address',
    label: 'Address',
    category: 'text',
    icon: '🏠',
    defaultConfig: {},
    supportsRequired: true,
    supportsConditional: true,
  },
  {
    type: 'calculated',
    label: 'Calculated',
    category: 'calculated',
    icon: '∑',
    defaultConfig: { formula: '' },
    supportsRequired: false,
    supportsConditional: false,
  },
  {
    type: 'currentuser',
    label: 'Submitted By',
    category: 'calculated',
    icon: '👤',
    defaultConfig: {},
    supportsRequired: false,
    supportsConditional: false,
  },
  {
    type: 'rating',
    label: 'Rating',
    category: 'choice',
    icon: '⭐',
    defaultConfig: { max: 5, labels: [] },
    supportsRequired: true,
    supportsConditional: true,
  },
  {
    type: 'section',
    label: 'Section Heading',
    category: 'layout',
    icon: '━',
    defaultConfig: {},
    supportsRequired: false,
    supportsConditional: false,
  },
  {
    type: 'pagebreak',
    label: 'Page Break',
    category: 'layout',
    icon: '⊞',
    defaultConfig: {},
    supportsRequired: false,
    supportsConditional: false,
  },
  {
    type: 'thankyou',
    label: 'Thank You',
    category: 'layout',
    icon: '✅',
    defaultConfig: { message: 'Thank you for your submission.' },
    supportsRequired: false,
    supportsConditional: false,
  },
];

export function getFieldDefinition(type: FieldType): FieldTypeDefinition | undefined {
  return FIELD_DEFINITIONS.find((d) => d.type === type);
}
